module.exports = {
    numberOfGames: 80,
    skillProb: 0.8,
    miscProb: 0.6,
    extraInfos: [
        "Organizer may be a bit late.",
        "Organizer is arriving late and hence needs someone to help with the setup.",
        "Please let organizer know if you haven't competed in awhile.",
        "Organizer is willing to drive.",
        "Organizer needs a ride.",
        "Organizer can drive people there, but not home.",
        "Organizer can drive people home, but not there.",
        "Organizer will bring snacks.",
        "Organizer cannot bring snacks this time.",
        "Someone else needs to bring snacks, this time.  Organizer is tired of doing it.",
        "Organizer will bring water.",
        "Organizer cannot bring water, this time.",
        "Organizer is hopeful that water will be available this time.",
        "It should be easy to park there.",
        "Does anyone know if it's be easy to park there?",
        "The location is along the bus route.",
        "The location is near the subway.",
        "The venue is near the highway.",
        "You don't need to pay to park.",
        "It is not very expensive to park.",
        "Friends/family are welcome to watch.",
        "Plenty of seating is available in the stands.",
        "This is the organizer's first time doing one of these things.",
        "Organizer will explain the 'drill' to the newcomers.",
        "Organizer will bring the uniforms.",
        "Each person should bring his/her own towel.",
        "Organizer will bring the towels.",
        "Organizer will bring the gear.",
        "Each person needs to bring his/her own gear.",
        "Organizer will purchase the gear beforehand.",
        "Lets rock!",
        "Organizer plans to do this throughout the year.",
    ],
    cities: [
    'New York City, NY',
    'Los Angeles, CA',
    'Chicago, IL',
    'Houston, TX',
    'Phoenix, AZ',
    'Philadelphia, PA',
    'San Antonio, TX',
    'San Diego, CA',
    'Dallas, TX',
    'Austin, TX',
    'San Jose, CA',
    'Fort Worth, TX',
    'Jacksonville, FL',
    'Columbus, OH',
    'Charlotte, NC',
    'Indianapolis, IN',
    'San Francisco, CA',
    'Seattle, WA',
    'Denver, CO',
    'Washington, DC',
    'Boston, MA',
    'El Paso, TX',
    'Nashville, TN',
    'Oklahoma City, OK',
    'Las Vegas, NV',
    'Detroit, MI',
    'Portland, OR',
    'Memphis, TN',
    'Louisville, KY',
    'Milwaukee, WI',
    'Baltimore, MD',
    'Albuquerque, NM',
    'Tucson, AZ',
    'Mesa, AZ',
    'Fresno, CA',
    'Sacramento, CA',
    'Atlanta, GA',
    'Kansas City, MO',
    'Colorado Springs, CO',
    'Raleigh, NC',
    'Omaha, NE',
    'Miami, FL',
    'Long Beach, CA',
    'Virginia Beach, VA',
    'Oakland, CA',
    'Minneapolis, MN',
    'Tampa, FL',
    'Tulsa, OK',
    'Arlington, TX',
    'Wichita, KS',
    'Bakersfield, CA',
    'Aurora, CO',
    'New Orleans, LA',
    'Cleveland, OH',
    'Anaheim, CA',
    'Henderson, NV',
    'Riverside, CA',
    'Santa Ana, CA',
    'Corpus Christi, TX',
    'Lexington, KY',
    'Stockton, CA',
    'St. Paul, MN',
    'Cincinnati, OH',
    'Greensboro, NC',
    'Pittsburgh, PA',
    'Irvine, CA',
    'St. Louis, MO',
    'Lincoln, NE',
    'Orlando, FL',
    'Durham, NC',
    'Plano, TX',
    'Anchorage, AK',
    'Newark, NJ',
    'Chula Vista, CA',
    'Fort Wayne, IN',
    'Chandler, AZ',
    'Toledo, OH',
    'St. Petersburg, FL',
    'Reno, NV',
    'Laredo, TX',
    'Scottsdale, AZ',
    'North Las Vegas, NV',
    'Lubbock, TX',
    'Madison, WI',
    'Gilbert, AZ',
    'Jersey City, NJ',
    'Glendale, AZ',
    'Buffalo, NY',
    'Winston-Salem, NC',
    'Chesapeake, VA',
    'Fremont, CA',
    'Norfolk, VA',
    'Irving, TX',
    'Garland, TX',
    'Paradise, NV',
    'Arlington, VA',
    'Richmond, VA',
    'Hialeah, FL',
    'Boise, ID',
    'Spokane, WA',
    'Frisco, TX',
    'Moreno Valley, CA',
    'Tacoma, WA',
    'Fontana, CA',
    'Modesto, CA',
    'Baton Rouge, LA',
    'Port St. Lucie, FL',
    'San Bernardino, CA',
    'McKinney, TX',
    'Fayetteville, NC',
    'Santa Clarita, CA',
    'Des Moines, IA',
    'Oxnard, CA',
    'Birmingham, AL',
    'Spring Valley, NV',
    'Huntsville, AL',
    'Rochester, NY',
    'Cape Coral, FL',
    'Tempe, AZ',
    'Grand Rapids, MI',
    'Yonkers, NY',
    'Overland Park, KS',
    'Salt Lake City, UT',
    'Amarillo, TX',
    'Augusta, GA',
    'Columbus, GA',
    'Tallahassee, FL',
    'Montgomery, AL',
    'Huntington Beach, CA',
    'Akron, OH',
    'Little Rock, AR',
    'Glendale, CA',
    'Grand Prairie, TX',
    'Aurora, IL',
    'Sunrise Manor, NV',
    'Ontario, CA',
    'Sioux Falls, SD',
    'Knoxville, TN',
    'Vancouver, WA',
    'Mobile, AL',
    'Worcester, MA',
    'Chattanooga, TN',
    'Brownsville, TX',
    'Peoria, AZ',
    'Fort Lauderdale, FL',
    'Shreveport, LA',
    'Newport News, VA',
    'Providence, RI',
    'Elk Grove, CA',
    'Rancho Cucamonga, CA',
    'Salem, OR',
    'Pembroke Pines, FL',
    'Santa Rosa, CA',
    'Eugene, OR',
    'Oceanside, CA',
    'Cary, NC',
    'Fort Collins, CO',
    'Corona, CA',
    'Enterprise, NV',
    'Garden Grove, CA',
    'Springfield, MO',
    'Clarksville, TN',
    'Lakewood, CO',
    'Alexandria, VA',
    'Hayward, CA',
    'Murfreesboro, TN',
    'Killeen, TX',
    'Hollywood, FL',
    'Lancaster, CA',
    'Salinas, CA',
    'Jackson, MS',
    'Midland, TX',
    'Macon County, GA',
    'Kansas City, KS',
    'Palmdale, CA',
    'Sunnyvale, CA',
    'Springfield, MA',
    'Escondido, CA',
    'Pomona, CA',
    'Bellevue, WA',
    'Surprise, AZ',
    'Naperville, IL',
    'Pasadena, TX',
    'Denton, TX',
    'Roseville, CA',
    'Joliet, IL',
    'Thornton, CO',
    'McAllen, TX',
    'Paterson, NJ',
    'Rockford, IL',
    'Carrollton, TX',
    'Bridgeport, CT',
    'Miramar, FL',
    'Round Rock, TX',
    'Metairie, LA',
    'Olathe, KS',
    'Waco, TX'
]};
