module.exports = {
    numberOfGames: 10,
    skillProb: 0.5,
    miscProb: 0.5,
    cities: [
    'New York City NY',
    'Los Angeles CA',
    'Chicago IL',
    'Houston TX',
    'Phoenix AZ',
    'Philadelphia PA',
    'San Antonio TX',
    'San Diego CA',
    'Dallas TX',
    'Austin TX',
    'San Jose CA',
    'Fort Worth TX',
    'Jacksonville FL',
    'Columbus OH',
    'Charlotte NC',
    'Indianapolis IN',
    'San Francisco CA',
    'Seattle WA',
    'Denver CO',
    'Washington DC',
    'Boston MA',
    'El Paso TX',
    'Nashville TN',
    'Oklahoma City OK',
    'Las Vegas NV',
    'Detroit MI',
    'Portland OR',
    'Memphis TN',
    'Louisville KY',
    'Milwaukee WI',
    'Baltimore MD',
    'Albuquerque NM',
    'Tucson AZ',
    'Mesa AZ',
    'Fresno CA',
    'Sacramento CA',
    'Atlanta GA',
    'Kansas City MO',
    'Colorado Springs CO',
    'Raleigh NC',
    'Omaha NE',
    'Miami FL',
    'Long Beach CA',
    'Virginia Beach VA',
    'Oakland CA',
    'Minneapolis MN',
    'Tampa FL',
    'Tulsa OK',
    'Arlington TX',
    'Wichita KS',
    'Bakersfield CA',
    'Aurora CO',
    'New Orleans LA',
    'Cleveland OH',
    'Anaheim CA',
    'Henderson NV',
    'Honolulu HI',
    'Riverside CA',
    'Santa Ana CA',
    'Corpus Christi TX',
    'Lexington KY',
    'San Juan PR',
    'Stockton CA',
    'St. Paul MN',
    'Cincinnati OH',
    'Greensboro NC',
    'Pittsburgh PA',
    'Irvine CA',
    'St. Louis MO',
    'Lincoln NE',
    'Orlando FL',
    'Durham NC',
    'Plano TX',
    'Anchorage AK',
    'Newark NJ',
    'Chula Vista CA',
    'Fort Wayne IN',
    'Chandler AZ',
    'Toledo OH',
    'St. Petersburg FL',
    'Reno NV',
    'Laredo TX',
    'Scottsdale AZ',
    'North Las Vegas NV',
    'Lubbock TX',
    'Madison WI',
    'Gilbert AZ',
    'Jersey City NJ',
    'Glendale AZ',
    'Buffalo NY',
    'Winston-Salem NC',
    'Chesapeake VA',
    'Fremont CA',
    'Norfolk VA',
    'Irving TX',
    'Garland TX',
    'Paradise NV',
    'Arlington VA',
    'Richmond VA',
    'Hialeah FL',
    'Boise ID',
    'Spokane WA',
    'Frisco TX',
    'Moreno Valley CA',
    'Tacoma WA',
    'Fontana CA',
    'Modesto CA',
    'Baton Rouge LA',
    'Port St. Lucie FL',
    'San Bernardino CA',
    'McKinney TX',
    'Fayetteville NC',
    'Santa Clarita CA',
    'Des Moines IA',
    'Oxnard CA',
    'Birmingham AL',
    'Spring Valley NV',
    'Huntsville AL',
    'Rochester NY',
    'Cape Coral FL',
    'Tempe AZ',
    'Grand Rapids MI',
    'Yonkers NY',
    'Overland Park KS',
    'Salt Lake City UT',
    'Amarillo TX',
    'Augusta GA',
    'Columbus GA',
    'Tallahassee FL',
    'Montgomery AL',
    'Huntington Beach CA',
    'Akron OH',
    'Little Rock AR',
    'Glendale CA',
    'Grand Prairie TX',
    'Aurora IL',
    'Sunrise Manor NV',
    'Ontario CA',
    'Sioux Falls SD',
    'Knoxville TN',
    'Vancouver WA',
    'Mobile AL',
    'Worcester MA',
    'Chattanooga TN',
    'Brownsville TX',
    'Peoria AZ',
    'Fort Lauderdale FL',
    'Shreveport LA',
    'Newport News VA',
    'Providence RI',
    'Elk Grove CA',
    'Rancho Cucamonga CA',
    'Salem OR',
    'Pembroke Pines FL',
    'Santa Rosa CA',
    'Eugene OR',
    'Oceanside CA',
    'Cary NC',
    'Fort Collins CO',
    'Corona CA',
    'Enterprise NV',
    'Garden Grove CA',
    'Springfield MO',
    'Clarksville TN',
    'Bayamon PR',
    'Lakewood CO',
    'Alexandria VA',
    'Hayward CA',
    'Murfreesboro TN',
    'Killeen TX',
    'Hollywood FL',
    'Lancaster CA',
    'Salinas CA',
    'Jackson MS',
    'Midland TX',
    'Macon County GA',
    'Kansas City KS',
    'Palmdale CA',
    'Sunnyvale CA',
    'Springfield MA',
    'Escondido CA',
    'Pomona CA',
    'Bellevue WA',
    'Surprise AZ',
    'Naperville IL',
    'Pasadena TX',
    'Denton TX',
    'Roseville CA',
    'Joliet IL',
    'Thornton CO',
    'McAllen TX',
    'Paterson NJ',
    'Rockford IL',
    'Carrollton TX',
    'Bridgeport CT',
    'Miramar FL',
    'Round Rock TX',
    'Metairie LA',
    'Olathe KS',
    'Waco TX'
]};
