module.exports = {
    reservationProb: 0.5,
    extraInfos: [
        "I'm getting over a cold.",
        "I may be a bit late.",
        "I'm arriving early and hence available to help with the setup.",
        "I haven't competed in awhile.",
        "I've competed a lot recently, so feel free to bench me.",
        "I'm willing to carpool.",
        "I can drive people there, but not home.",
        "I can drive people home, but not there.",
        "I can bring snacks.",
        "I cannot bring snacks this time.",
        "Someone else needs to bring snacks, this time.  I'm tired of doing it myself.",
        "I can bring water.",
        "I cannot bring water, this time.",
        "I hope that water is available, this time.",
        "I hope that it is easy to park there.",
        "Can you confirm that it'll be easy to park there?",
        "Please confirm that the location is along the bus route.",
        "Please confirm that the location is near the subway.",
        "I hope that the venue is near the highway.",
        "I hope that we don't need to pay to park.",
        "I hope that it is not too expensive to park.",
        "My partner is coming to watch.",
        "Will there be seating?",
        "This is my first time doing one of these things.",
        "Someone needs to explain the 'drill' to the newcomers.",
        "I'll bring the uniforms.",
        "Someone needs to bring the towels.",
        "We need someone to bring the gear.",
        "I'll purchase the gear beforehand.",
        "These things rock!",
        "I hope that we still do this during the winter.",
    ]
 };
