module.exports = {
  numberOfUsers: 2,
  people :[
    ['Aaron', 'Pittsburgh PA'],
    ['Ben', 'Denver CO'],
    ['Curtis', 'San Francisco CA'],
    ['Darius', 'Muscle Shoals AL'],
    ['Ed', 'Scranton PA'],
    ['Fred', 'Glen Rock NJ'],
    ['Geoffrey', 'Sacramento CA'],
    ['Hal', 'Annapolis MD'],
    ['Ian', 'Brooklyn NY'],
    ['Javier', 'San Diego CA'],
    ['Krisna', 'Las Vegas NV'],
    ['Lauren', 'Seattle WA'],
    ['Mylo', 'Los Angeles CA'],
    ['Nick', 'Houston TX'],
    ['Olive', 'Baltimore MD'],
    ['Pete', 'Stratford CT'],
    ['Quincy', 'Memphis TN'],
    ['Rose', 'Palo Alto CA'],
    ['Simon', 'Boston MA'],
    ['Tyna', 'Miami Gardens FL'],
    ['Ugo', 'Chicago IL'],
    ['Vann', 'Hollywood CA'],
    ['Warren', 'Portland OR'],
    ['Xavier', 'St Louis, MO'],
    ['Yul', 'Severna Park MD'],
    ['Zachery', 'Little Rock AK']
  ]};
